In [27]:
# What is being done is described in python comments and what the fucntion is performing is stated after the code is run and 
# described in markdown section

In [28]:
from __future__ import print_function
import torch

In [29]:
# Construting an uninitialized values of dimension 5,3

In [30]:
x=torch.empty(5,3)
print(x)

tensor([[1.0286e-38, 9.0919e-39, 8.9082e-39],
        [9.2755e-39, 8.4490e-39, 1.0745e-38],
        [1.1112e-38, 9.2755e-39, 8.7245e-39],
        [9.9184e-39, 9.2755e-39, 1.0653e-38],
        [9.7347e-39, 1.0194e-38, 1.0745e-38]])


In [31]:
#since the matrix is uninitialized so it prints Garbage values

In [32]:
# initializing the matrix with random numbers ranging from 0-1

In [33]:
x=torch.rand(5,3)
print(x)

tensor([[0.9181, 0.4410, 0.1309],
        [0.8206, 0.9409, 0.7067],
        [0.1731, 0.8469, 0.1182],
        [0.4830, 0.9240, 0.7922],
        [0.4911, 0.2809, 0.3543]])


In [34]:
#constructing a matrix filled with zeros and of dtype long

In [35]:
x=torch.zeros(5,3,dtype=torch.long)

In [36]:
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [37]:
#constructing a tensor directly from the data

A tensor is often thought of as a generalized matrix. That is, it could be a 1-D matrix (a vector is actually such a tensor), a 3-D matrix (something like a cube of numbers), even a 0-D matrix (a single number), or a higher dimensional structure that is harder to visualize. The dimension of the tensor is called its rank.

In [38]:
x=torch.tensor([5,3])
print(x)

tensor([5, 3])


In [39]:
x=x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [40]:
x=torch.ones(5,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


So, essentially, new_ones allows you to quickly create a new torch.Tensor on the same device and data type as a previously existing tensor (with ones), whereas ones() serves the purpose of creating a torch.Tensor from scratch (filled with ones).

In [41]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)   

tensor([[ 3.4390, -0.5486,  0.6965],
        [ 0.6636,  0.3343,  0.2640],
        [ 1.3873,  1.1922,  0.6310],
        [ 0.6534,  1.3091,  0.1797],
        [ 0.4182, -0.3990,  1.2441]])


rand_n ---> random distribution of numbers

rand_n_like---> takes it's first argument the matrix jiske like use banana hai here x ,so typically if here we do not pass the dimension and randn_like mutates over x

In [42]:
#get the size

In [44]:
print(x.size())

torch.Size([5, 3])


torch.Size is in fact a tuple, so it supports all tuple operations.

In [45]:
# Operations

In [48]:
#addition

In [49]:
y=torch.rand(5,3)

In [50]:
print(x+y)

tensor([[ 4.4016,  0.4263,  1.6553],
        [ 0.9047,  0.9987,  0.6182],
        [ 1.4640,  1.4735,  0.9755],
        [ 1.0623,  2.0190,  1.1073],
        [ 1.1553, -0.0291,  1.5365]])


In [51]:
#or

In [52]:
print(torch.add(x,y))

tensor([[ 4.4016,  0.4263,  1.6553],
        [ 0.9047,  0.9987,  0.6182],
        [ 1.4640,  1.4735,  0.9755],
        [ 1.0623,  2.0190,  1.1073],
        [ 1.1553, -0.0291,  1.5365]])


In [54]:
result=torch.empty(5,3)
print(result)

tensor([[ 4.4016,  0.4263,  1.6553],
        [ 0.9047,  0.9987,  0.6182],
        [ 1.4640,  1.4735,  0.9755],
        [ 1.0623,  2.0190,  1.1073],
        [ 1.1553, -0.0291,  1.5365]])


In [55]:
# providing an output tensor as argument


In [56]:
torch.add(x,y,out=result)
print(result)

tensor([[ 4.4016,  0.4263,  1.6553],
        [ 0.9047,  0.9987,  0.6182],
        [ 1.4640,  1.4735,  0.9755],
        [ 1.0623,  2.0190,  1.1073],
        [ 1.1553, -0.0291,  1.5365]])


In [57]:
# addition in_place

In [58]:
#adding x to y

In [59]:
y.add_(x)

tensor([[ 4.4016,  0.4263,  1.6553],
        [ 0.9047,  0.9987,  0.6182],
        [ 1.4640,  1.4735,  0.9755],
        [ 1.0623,  2.0190,  1.1073],
        [ 1.1553, -0.0291,  1.5365]])

In [60]:
print(y)

tensor([[ 4.4016,  0.4263,  1.6553],
        [ 0.9047,  0.9987,  0.6182],
        [ 1.4640,  1.4735,  0.9755],
        [ 1.0623,  2.0190,  1.1073],
        [ 1.1553, -0.0291,  1.5365]])


Any operation that mutates a tensor in-place is post-fixed with an _(underscore). For example: x.copy(underscore)(y), x.t(underscore)(), will change x.

In [62]:
print(x)

tensor([[ 3.4390, -0.5486,  0.6965],
        [ 0.6636,  0.3343,  0.2640],
        [ 1.3873,  1.1922,  0.6310],
        [ 0.6534,  1.3091,  0.1797],
        [ 0.4182, -0.3990,  1.2441]])


In [63]:
#slicing

In [64]:
print(x[:,1])

tensor([-0.5486,  0.3343,  1.1922,  1.3091, -0.3990])


In [67]:
#resizing and reshaping of array can be done using view

In [68]:
x=torch.randn(4,4)

In [70]:
y=x.view(16)

In [77]:
z=x.view(-1,8) # the size -1 is inferred from other dimensions

In [76]:
print(x.size())

torch.Size([4, 4])


In [73]:
print(y.size())

torch.Size([16])


In [74]:
print(z.size())

torch.Size([2, 8])


-1 parameter calculates things for us ki ek dimesnion agar hum kuch dalte hai to agli dimension kya honi chiye 

also agar hum isme koi dimension dalte hai jo ki 4*4=16 k jaise nahi ati hai to uska resize nahi ho skta for instance 8*2 ho skta hai but not 7*3

In [79]:
# If you have a one element tensor, use .item() to 
# get the value as a Python number

In [82]:
x=torch.randn(1)
print(x)
print(x.item())

tensor([0.4363])
0.4362821877002716


# Numpy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

In [83]:
# Converting a Torch Tensor to a Numpy array

In [86]:
a=torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [89]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [90]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [91]:
print(a)

tensor([2., 2., 2., 2., 2.])


In [92]:
print(b)

[2. 2. 2. 2. 2.]


In [93]:
# Converting Numpy array to torch tensor

In [100]:
import numpy as np
a=np.ones(5)

In [101]:
print(a)

[1. 1. 1. 1. 1.]


In [102]:
b=torch.from_numpy(a)

In [103]:
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [104]:
np.add(a,1,out=a)

array([2., 2., 2., 2., 2.])

In [105]:
print(a)

[2. 2. 2. 2. 2.]


In [106]:
print(b)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.